// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPZVQUMa1RjYpTbaHVOLu9M5JoilKTZSI',
    appId: '1:547822238192:web:56de40b96a9e2504ae4535',
    messagingSenderId: '547822238192',
    projectId: 'cityfix-3317c',
    authDomain: 'cityfix-3317c.firebaseapp.com',
    storageBucket: 'cityfix-3317c.firebasestorage.app',
    measurementId: 'G-QTM9TB5J3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrtzTmRqLMkteSnOXKgLvoQKDl5jwl5Co',
    appId: '1:547822238192:android:69caa2cf87fa5f68ae4535',
    messagingSenderId: '547822238192',
    projectId: 'cityfix-3317c',
    storageBucket: 'cityfix-3317c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj0_4A_P5eCKdGRxrBtIEcKPxyHFIrKeI',
    appId: '1:547822238192:ios:643a066a7bbeb751ae4535',
    messagingSenderId: '547822238192',
    projectId: 'cityfix-3317c',
    storageBucket: 'cityfix-3317c.firebasestorage.app',
    iosClientId: '547822238192-op0d8k9tu2shk44cc138g923a3oaum25.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityFixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj0_4A_P5eCKdGRxrBtIEcKPxyHFIrKeI',
    appId: '1:547822238192:ios:643a066a7bbeb751ae4535',
    messagingSenderId: '547822238192',
    projectId: 'cityfix-3317c',
    storageBucket: 'cityfix-3317c.firebasestorage.app',
    iosClientId: '547822238192-op0d8k9tu2shk44cc138g923a3oaum25.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityFixApp',
  );
}
